name: "PHP"
on: [push]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v1
      - name: Environment
        run: php -r "file_exists('.env') || copy('.env.tests', '.env');"
      - name: Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Encryption
        run: php artisan key:generate
      - name: SQLite
        run: touch database/database.sqlite
      - name: Schemas
        run: php artisan migrate
      - name: Testing
        run: php artisan test
